### ISSUE TITLE
Validate JSON

### ISSUE THREAD

**Issue by jeroen** [ropenscilabs/datapkg#6]
Using https://github.com/ropenscilabs/jsonvalidate. @pwalsh where can I find the schema for data packages?

**Comment by pwalsh** [comment]
@jeroenooms 

The Tabular Data Package Profile is here: http://schemas.datapackages.org/tabular-data-package.json

FYI, we have a [registry of different schemas here](http://schemas.datapackages.org/registry.csv) and we load different profiles from here dynamically in Python and JS libs. [Example](https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/registry.py#L15). Because R _only_ needs _Tabular_ data package support, I guess you only need that particular profile.

**Comment by jeroen** [comment]
We now have a `datapkg_validate` function: https://github.com/ropenscilabs/datapkg/commit/14dad38cac4d929405aaea2f6bdbff8843880594
